{{- if eq .Values.useRabbitMQ true }}
apiVersion: v1
data:
  rabbitmq_enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_amqp1_0].
kind: ConfigMap
metadata:
  name: rabbitmq-enabled-plugins
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.orderService.queueUsername | b64enc  }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.orderService.queuePassword | b64enc  }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
      - name: rabbitmq
        {{- if .Values.imageRegistry }}
        image: {{ .Values.imageRegistry }}/{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        {{- else }}
        image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        {{- end }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "username"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
          requests:
            memory: 128Mi
            cpu: 75m
        ports:
        - containerPort: 5672
        - containerPort: 15672
        startupProbe:
          periodSeconds: 10
          failureThreshold: 30
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
        readinessProbe:
          periodSeconds: 10
          failureThreshold: 3
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
        livenessProbe:
          periodSeconds: 10
          failureThreshold: 3
          tcpSocket:
            port: 5672
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
{{- end }}