apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: store-admin
        {{- if .Values.imageRegistry }}
        image: {{ .Values.imageRegistry }}/{{ .Values.storeAdmin.image.repository }}:{{ .Values.storeAdmin.image.tag }}
        {{- else }}
        image: {{ .Values.storeAdmin.image.repository }}:{{ .Values.storeAdmin.image.tag }}
        {{- end }}
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 10
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 10
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 10
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: {{ .Values.storeAdmin.serviceType }}
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: store-admin