apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-customer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: virtual-customer
  template:
    metadata:
      labels:
        app: virtual-customer
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: virtual-customer
        {{- if .Values.imageRegistry }}
        image: {{ .Values.imageRegistry }}/{{ .Values.virtualCustomer.image.repository }}:{{ .Values.virtualCustomer.image.tag }}
        {{- else }}
        image: {{ .Values.virtualCustomer.image.repository }}:{{ .Values.virtualCustomer.image.tag }}
        {{- end }}
        env:
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3000"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 50Mi
            cpu: 20m
          limits:
            memory: 100Mi
            cpu: 50m
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3